CREATE DATABASE SalePcDB;

CREATE TABLE Users (
	UserID INT PRIMARY KEY IDENTITY(1,1),
	Username NVARCHAR(50) NOT NULL,
	Password NVARCHAR(255) NOT NULL,
	Position NVARCHAR(50) NOT NULL,
);
CREATE TABLE Products (
	ProductID INT PRIMARY KEY IDENTITY(1,1),
	CatagoryID INT NOT NULL,
	ProductName NVARCHAR(100) NOT NULL,
	Price DECIMAL(18, 2) NOT NULL,
	Stock INT NOT NULL,
);
CREATE TABLE Orders (
	OrderID INT PRIMARY KEY IDENTITY(1,1),
	UserID INT NOT NULL,
	OrderDate DATETIME NOT NULL DEFAULT GETDATE(),
	TotalAmount DECIMAL(18, 2) NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Dell
 (
	DellID INT PRIMARY KEY IDENTITY(1,1),
	ProductID INT NOT NULL,
	DellColor NVARCHAR(50) NOT NULL,
	DellPrice FLOAT NOT NULL,
	DellStock INT NOT NULL,
	DellDescription NVARCHAR(255) NOT NULL,
	FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

CREATE TABLE Asus
 (
	AsusID INT PRIMARY KEY IDENTITY(1,1),
	ProductID INT NOT NULL,
	AsusName NVARCHAR(100) NOT NULL,
	AsusPrice FLOAT NOT NULL,
	AsusStock INT NOT NULL,
	AsusDescription NVARCHAR(255) NOT NULL,
	FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

CREATE TABLE MSI
 (
	MsiID INT PRIMARY KEY IDENTITY(1,1),
	ProductID INT NOT NULL,
	MsiName NVARCHAR(100) NOT NULL,
	MsiPrice FLOAT NOT NULL,
	MsiStock INT NOT NULL,
	MsiDescription NVARCHAR(255) NOT NULL,
	FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

CREATE TABLE Lenovo
 (
	LenovoID INT PRIMARY KEY IDENTITY(1,1),
	ProductID INT NOT NULL,
	LenovoName NVARCHAR(100) NOT NULL,
	LenovoPrice FLOAT NOT NULL,
	LenovoStock INT NOT NULL,
	LenovoDescription NVARCHAR(255) NOT NULL,
	FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);